language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

install:
    - yarn install

script:
    - yarn lint
    - yarn test
    - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
  