export const CACHE_SEARCHER = 'CACHE_SEARCHER';
export const BEFORE_ARTICLE_SEARCH = 'BEFORE_ARTICLE_SEARCH';
export const AFTER_ARTICLE_SEARCH_COMPLETED = 'AFTER_ARTICLE_SEARCH_COMPLETED';
export const BEFORE_ARTICLE_FETCH_MORE_SEARCH = 'BEFORE_ARTICLE_FETCH_MORE_SEARCH';
export const AFTER_ARTICLE_FETCH_MORE_SEARCH_COMPLETED = 'AFTER_ARTICLE_FETCH_MORE_SEARCH_COMPLETED';
