export const NOTIFICATION_REQUESTED = 'NOTIFICATION_REQUESTED';
export const NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE';
export const NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE';
export const NOTIFICATION_REMOVE_REQUEST = 'NOTIFICATION_REMOVE_REQUEST';
export const NOTIFICATION_UPDATE_PENDING = 'NOTIFICATION_UPDATE_PENDING';
