export const FETCH_YOUTUBE_LIST = 'FETCH_YOUTUBE_LIST';
export const FETCH_YOUTUBE_LIST_SUCCESS = 'FETCH_YOUTUBE_LIST_SUCCESS';
export const FETCH_MORE_YOUTUBE_LIST_SUCCESS = 'FETCH_MORE_YOUTUBE_LIST_SUCCESS';
export const CLEAR_YOUTUBE_RESULT = 'CLEAR_YOUTUBE_RESULT';
export const UPDATE_YOUTUBE_LOADING = 'UPDATE_YOUTUBE_LOADING';
